### ISSUE TITLE
Mines doesnt format properly on compact mode

### ISSUE THREAD

**Issue by TheSorton** [TheSorton/Arisubot#1]
Needs an extra line at the top. Perhaps a title will be best suited for this

**Comment by TheSorton** [comment]
[Using an embed instead. Seems to work better.](https://i.alan.moe/gcq3q.png)

**Comment by TheSorton** [comment]
I've decided to not worry about the spacing issue since its too much of a headache. I *could* take off the embed and add two lines for compact mode, however its make *normal* people on cozy mode see two line breaks instead. 

Perhaps I should flip a coin?

**Comment by jozsefsallai** [comment]
Compact mode is.........quite big of a headache. I decided to just roll with it and not care about it too much. 

My bot does this, it's ok for both compact and cozy mode users:
![image](https://user-images.githubusercontent.com/20266711/57986921-97f17900-7a83-11e9-85fd-e09c73921e9e.png)

you can try somethign like that

**Comment by TheSorton** [comment]
Yeah I'm not a fan of compact mode either. I just threw it into an embed and called it good. 
Your suggestion is probably a better solution all around. 

Though I'm a little *too* busy to work on the bot presently. I'll keep that in mind though.
