### ISSUE TITLE
Fix newlines in `say` command

### ISSUE THREAD

**Issue by FungiOfDeath** [TheSorton/Arisubot#8]
# Current Behavior

If the user types (assuming prefix is `/`) `/say hello world` the bot will reply with:
```
hello
world
```

# Expected Behavior

In the above situation, the bot should respond with:
```
hello world
```

# Diagnosis and Suggested Solution

## Diagnosis

When the `say` body is called, it uses `args` to reply. However, `args` is split into an array instead of being a simple string. As a result, when the command calls
```js
message.channel.send(args);
```
it prints each element on its own line.

## Solution

In `onMessage`, pass a field into the command bodies (suggested name: `exactMessage`) which has had very little processing done: namely, had the prefix removed.

Then, inside the `say` command, print the `exactMessage` field instead of the `args` field.

**Alternatively**, don't modify `onMessage`. Instead, modify the `say` command to get the content of the `message` field passed to it and use that instead.

**Comment by FungiOfDeath** [comment]
`args` is split in `getargs` (found in `add-commands.js`) via the following line:
```js
message.content.slice(config.prefix.length).trim().split(/ +/g)
```

**Comment by FungiOfDeath** [comment]
# Potential Edge Cases

Should the command (replacing spaces with underscores for technical reasons) `/say hello _________ world` reply with
```
hello           world
```
or
```
hello world
```

In other words, should the number of spaces be normalized to one, or should the amount of whitespace be preserved?

**Comment by TheSorton** [comment]
Preserved. My intention for say is to repeat exactly what the user gives. 

However, if it's too much trouble, normalized.

**Comment by FungiOfDeath** [comment]
Should be easy to preserve. Should be able to make a push shortly.
